# Generated by Django 3.2.16 on 2022-12-20 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='role_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=250, verbose_name='Role Name')),
                ('rolecode', models.CharField(max_length=50, verbose_name='Role Code')),
                ('roledesc', models.CharField(max_length=250, verbose_name='Role Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=25)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_master_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_master_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'db_table': 'role_master',
            },
        ),
        migrations.CreateModel(
            name='menu_master1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuname', models.CharField(max_length=250, verbose_name='Menu Name')),
                ('menuurl', models.CharField(max_length=50, verbose_name='Menu URL')),
                ('menudesc', models.CharField(max_length=250, verbose_name='Menu Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=25)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_master1_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('menu_parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_menu_master1_fk', to='rolerights.menu_master1')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_master1_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'db_table': 'menu_master1',
            },
        ),
    ]
