# Generated by Django 3.2.16 on 2022-12-20 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rolerights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='role_menu_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_menu_map_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('menu_master', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menu_master_fk', to='rolerights.menu_master1')),
                ('role_master', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='role_master_fk', to='rolerights.role_master')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_menu_map_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'db_table': 'role_menu_map',
            },
        ),
        migrations.AddConstraint(
            model_name='role_menu_map',
            constraint=models.UniqueConstraint(fields=('role_master', 'menu_master'), name='role_master_Unique'),
        ),
    ]
