# Generated by Django 3.2.16 on 2022-12-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolerights', '0002_auto_20221220_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_menu_map',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='role_menu_map',
            name='updated_by',
        ),
    ]
