# Generated by Django 3.2.16 on 2022-12-26 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rolerights', '0004_auto_20221226_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_map_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('role_master', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='role1_master_fk', to='rolerights.role_master')),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_map_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('user_master', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_map',
            },
        ),
    ]
