# Generated by Django 3.2.16 on 2023-01-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolerights', '0006_menu_master1_iconn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_master1',
            name='iconn',
            field=models.CharField(blank=True, default='fa fa-circle', max_length=50, null=True, verbose_name='Icon'),
        ),
    ]
