# Generated by Django 3.2.18 on 2023-04-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Internal', models.FloatField(max_length=200)),
                ('External', models.FloatField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Semester', models.CharField(max_length=200)),
                ('Total', models.FloatField(max_length=200)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
