# Generated by Django 4.1.7 on 2023-02-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField(max_length=20)),
                ('Name', models.CharField(max_length=200)),
                ('Internal', models.FloatField(max_length=200)),
                ('External', models.FloatField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Semester', models.CharField(max_length=200)),
                ('Total', models.FloatField(max_length=200)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
