# Generated by Django 3.2.18 on 2023-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='No',
            field=models.IntegerField(),
        ),
    ]
