# Generated by Django 3.2.18 on 2023-03-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_records_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_n', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['class_n'],
            },
        ),
        migrations.CreateModel(
            name='Organisation_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['org_name'],
            },
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_n', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['semester_n'],
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_n', models.CharField(max_length=200, unique=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.class')),
            ],
            options={
                'ordering': ['subject_n'],
            },
        ),
        migrations.CreateModel(
            name='Marks_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Internal', models.FloatField(default=0.0, max_length=200)),
                ('External', models.FloatField(default=0.0, max_length=200)),
                ('Total', models.FloatField(max_length=200)),
                ('Organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organisation_master')),
                ('Semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.semesters')),
                ('Subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subjects')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.class')),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
