# Generated by Django 3.2.18 on 2023-03-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_class_marks_data_organisation_master_semesters_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_n', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['semester_n'],
            },
        ),
        migrations.AlterField(
            model_name='marks_data',
            name='Semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sems'),
        ),
    ]
