# Generated by Django 3.2.18 on 2023-03-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20230303_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks_data',
            name='Semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.semesters'),
        ),
        migrations.DeleteModel(
            name='Sems',
        ),
    ]
