# Generated by Django 3.2.18 on 2023-03-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20230303_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='sem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.semesters'),
        ),
    ]
