# Generated by Django 3.2.18 on 2023-03-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_class_class_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='sem',
        ),
    ]
