# Generated by Django 3.2.18 on 2023-03-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20230303_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='standard_t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.class'),
        ),
    ]
