# Generated by Django 3.2.18 on 2023-03-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_student_uid_no_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks_data',
            name='unique_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='uid_no_n',
        ),
        migrations.AddField(
            model_name='student',
            name='uid_no',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UID',
        ),
    ]
