# Generated by Django 3.2.18 on 2023-03-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20230303_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organisation_master'),
        ),
        migrations.AddField(
            model_name='student',
            name='Organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organisation_master'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='Organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organisation_master'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organisation_master'),
        ),
        migrations.AddField(
            model_name='test',
            name='Organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organisation_master'),
        ),
    ]
